version: '3'
services:
  php: 
    build: ./php
    volumes:
      - ./src/my-app:/var/www
  
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./src/my-app:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
