services:
  php:
    build: ./docker/php
    volumes:
      - ./src:/var/www

  nginx:
    build: ./docker/nginx
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www
    depends_on:
      - php

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: laravel

volumes:
  mysql-data:
